enum HttpStatusCode {
  SUCCESS,
  PERMANENT_REDIRECTED,
  TEMPORARY_REDIRECTED,
  NOT_MODIFIED,
  BAD_REQUEST,
  UNAUTHORIZED_ERROR,
  FORBIDDEN,
  NOT_FOUND,
  INTERNAL_SERVER_ERROR,
  NOT_IMPLEMENTED
}
